name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Test and Coverage Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add runner user to the input group.
      run: sudo gpasswd -a $USER input

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libudev-dev \
          libinput-dev \
          libxkbcommon-dev

    - name: Install Rust stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install cargo-tarpaulin
      # Install tarpaulin via cargo to ensure it's available in the PATH
      run: |
        cargo install cargo-tarpaulin --locked --force

    - name: Create empty user config
      run: |
        mkdir -p /home/runner/.config/clefd
        touch /home/runner/.config/clefd/clefdrc

    - name: Run tests with coverage and enforce 70% minimum
      run: |
        cargo tarpaulin --verbose --fail-under 70
